In [11]:
class SoccerPlayer( object):
    def __init__ (self, name : str, position : str, back_number : int):
        self.name = name
        self.position = position
        self.back_number = back_number
    
    def __str__(self):
        return "Hello, My name is %s. My back number is %d" % \
                (self.name, self.back_number)
        
    def __add__(self, other):
        return self.name + other.name

In [12]:
abc = SoccerPlayer("son", "FW", 7)
park = SoccerPlayer("park", "WF", 13)

In [8]:
print(abc)

Hello, My name is son. My back number is 7


In [13]:
abc + park

'sonpark'

In [14]:
class SoccerPlayer( object):
    def __init__ (self, name : str, position : str, back_number : int):
        self.name = name
        self.position = position
        self.back_number = back_number
    
    def change_back_number(self, new_number):
        print("선수의 등번호를 변경합니다 : From %d to %d" % \
                (self.back_number, new_number))
        self.back_number = new_number
    
    def __str__(self):
        return "Hello, My name is %s. My back number is %d" % \
                (self.name, self.back_number)
        
    

In [15]:
choi = SoccerPlayer("Jinhyun", "MF", 10)
print(choi)

Hello, My name is Jinhyun. My back number is 10


In [16]:
choi.change_back_number(7)
print(choi)

선수의 등번호를 변경합니다 : From 10 to 7
Hello, My name is Jinhyun. My back number is 7


In [17]:
choi.back_number = 20
print(choi)

Hello, My name is Jinhyun. My back number is 20


In [19]:
choi.back_number

20

In [20]:
class Note(object):
    def __init__(self, content = None):
        self.content = content
    
    def write_content(self, content):
        self.content = content
    
    def remove_alll(self):
        self.content = ""
        
    def __add__(self, other):
        return self.content + other.content
    
    def __str__(self):
        return self.content
    

In [21]:
class NoteBook(object):
    def __init__(self, title):
        self.title = title
        self.page_number = 1
        self.notes = {}
        
    def add_note(self, note, page = 0):
        if self.page_number < 300:
            if page == 0:
                self.notes[self.page_number] = note
                self.page_number += 1
            else: 
                self.notes = {page : note}
                self.page_number += 1
        else:
            print("Page가 모두 채워졌습니다.")
            
    def remove_note(self, page_number):
        if page_number in self.notes.keys():
            return self.notes.pop(page_number)
        else:
            print("해당 페이지는 존재하지 않습니다")
            
    def get_number_of_pages(self):
        return len(self.notes.keys())

### Inheritance

In [22]:
class Person(object):
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def __str__(self):
        return "저의 이름은 {0} 입니다. 나이는 {1} 입니다".format(
            self.name, self.age
        )

In [23]:
class Korean(Person):
    pass

In [24]:
first_korean = Korean("Sooman", 35)
print(first_korean)

저의 이름은 Sooman 입니다. 나이는 35 입니다


In [25]:
class Person(object):
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender
        
    def about_me(self):
        print("저의 이름은 ", self.name, "이구요, 제 나이는 ", str(self.age) ,"살 입니다")
        
    def __str__(self):
        return "저의 이름은 ", self.name, "이구요, 제 나이는 ", str(self.age) ,"살 입니다"

In [26]:
class Employee(Person):
    def __init__(self, name, age, gender, salary, hire_date):
        super().__init__(name, age, gender)
        self.salary = salary
        self.hire_date = hire_date
        
    def do_work(self):
        print("열심히 일을 합니다.")
        
    def about_me(self):
        super().about_me()
        print("제 급여는 ", self.salary, "원 이구요, 제 입사일은 ", self.hire_date ," 입니다")

In [30]:
myPesron = Person("John", 34, "Male")
myPerson.about_me()

저의 이름은  John 이구요, 제 나이는  34 살 입니다


In [32]:
myEmployee = Employee("Daeho", 34, "Male", 300000, "2012/03/01")
myEmployee.about_me()

저의 이름은  Daeho 이구요, 제 나이는  34 살 입니다
제 급여는  300000 원 이구요, 제 입사일은  2012/03/01  입니다


In [33]:
class Animal:
    def __init__(self, name):
        self.name = name
    
    def talk(self):
        raise NotImplementedError("Subclass must implement abstract method")

In [34]:
class Cat(Animal):
    def talk(self):
        return 'Meow!'

class Dog(Animal):
    def talk(self):
        return 'Woof! Woof!'

In [35]:
animals = [Cat('Missy'), Cat('Mr. Mistoffelees'), Dog('Lassie')]

for animal in animals:
    print(animal.name + ": " + animal.talk())

Missy: Meow!
Mr. Mistoffelees: Meow!
Lassie: Woof! Woof!


### Visibility

In [36]:
class Product(object):
    pass

In [38]:
class Inventory(object):
    def __init__(self):
        self.items = []
        self.test = "abc"
        
    def add_new_item(self, product):
        if type(product) == Product:
            self.items.append(product)
            print("new item added")
        else:
            raise ValueError("Invalid Item")
            
    def get_number_of_item(self):
        return len(self.items)

In [39]:
my_inventory = Inventory()
my_inventory.add_new_item(Product())
my_inventory.add_new_item(Product())

new item added
new item added


In [40]:
my_inventory.items.append("abc")

In [41]:
my_inventory.items

 'abc']

In [42]:
class Inventory(object):
    def __init__(self):
        self.__items = []
        
    def add_new_item(self, product):
        if type(product) == Product:
            self.__items.append(product)
            print("new item added")
        else:
            raise ValueError("Invalid Item")
            
    def get_number_of_item(self):
        return len(self.items)

In [43]:
my_inventory = Inventory()
my_inventory.add_new_item(Product())
my_inventory.add_new_item(Product())
my_inventory

new item added
new item added


In [45]:
my_inventory.__items.append("abc")

AttributeError: 'Inventory' object has no attribute '__items'

In [46]:
 class Inventory(object):
    def __init__(self):
        self.__items = []
        
    def add_new_item(self, product):
        if type(product) == Product:
            self.__items.append(product)
            print("new item added")
        else:
            raise ValueError("Invalid Item")
            
    def get_number_of_item(self):
        return len(self.items)
    
    @property
    def items(self):
        return self.__items

In [47]:
my_inventory = Inventory()
my_inventory.add_new_item(Product())
my_inventory.add_new_item(Product())
my_inventory

new item added
new item added


In [48]:
my_inventory.__items

AttributeError: 'Inventory' object has no attribute '__items'

In [49]:
my_inventory.items

[<__main__.Product at 0x2655fa8f198>, <__main__.Product at 0x2655fa8fb70>]

In [50]:
my_inventory.items.append('a')

In [52]:
my_inventory.items

[<__main__.Product at 0x2655fa8f198>, <__main__.Product at 0x2655fa8fb70>, 'a']

### decorate

In [53]:
def square(x):
    return x * x

In [54]:
f = square

In [55]:
f(5)

25

In [56]:
def cube(x):
    return x*x*x

def formula(method, argument_list):
    return [method(value) for value in argument_list]

In [58]:
argument_list = [1,2,3,4]

formula(cube, argument_list)

[1, 8, 27, 64]

In [59]:
def print_msg(msg):
    def printer():
        print(msg)
    printer()
    
print_msg("Hello, Python")

Hello, Python


In [3]:
 def print_msg(msg):
    def printer():
        print(msg)
    return printer

another = print_msg("Hello, Python")
another()

Hello, Python


In [4]:
def tag_func(tag, text):
    text = text
    tag = tag
    
    def inner_func():
        return '<{0}>{1}<{0}>'.format(tag, text)
    
    return inner_func

h1_func = tag_func('title', "This is Python Class")
p_func = tag_func('p', "Data Academy")

In [1]:
def star(func):
    def inner(*args, **kwargs):
        print("*" * 30)
        func(*args, **kwargs)
        print("*" * 30)
    return inner

@star 
def printer(msg):
    print(msg)
printer("Hello")

******************************
Hello
******************************


In [2]:
def generate_power(exponent):
    def wrapper(f):
        def inner(*args):
            result = f(*args)
            return exponent**result
        return inner
    return wrapper

@generate_power(2)
def raise_two(n):
    return n**2

print(raise_two(7))

562949953421312


### Exception

In [7]:
a = [1, 2, 3, 4, 5]

for i in range(10):
    try:
        print(i, 10 // i)
        print(a[i])
        print(v)
    except ZeroDivisionError:
        print("Error")
        print("Not divided by 0")
    except IndexError as e:
         print(e)
    except Exception as e:
         print(e)

Error
Not divided by 0
1 10
2
name 'v' is not defined
2 5
3
name 'v' is not defined
3 3
4
name 'v' is not defined
4 2
5
name 'v' is not defined
5 2
list index out of range
6 1
list index out of range
7 1
list index out of range
8 1
list index out of range
9 1
list index out of range


In [8]:
for i in range(10):
    try:
        result = 10 // i
    except ZeroDivisionError:
        print("Not divided by 0")
    else:
        print(10 // i)

Not divided by 0
10
5
3
2
2
1
1
1
1


In [9]:
for i in range(10):
    try:
        result = 10 // i
    except ZeroDivisionError:
        print("Not divided by 0")
    else:
        print(10 // i)
    finally:
        print(i, "------", result)

Not divided by 0
0 ------ 1
10
1 ------ 10
5
2 ------ 5
3
3 ------ 3
2
4 ------ 2
2
5 ------ 2
1
6 ------ 1
1
7 ------ 1
1
8 ------ 1
1
9 ------ 1


In [ ]:
while True:
    value = input("변환할 정수값을 입력해주세요")
    for digit in value:
        if digit in value:
            if digit not in "0123456789":
                raise ValueError("숫자값을 입력하지 않으셨습니다.")
    print("정수값으로 변환된 숫자 -", int(value))

In [1]:
def get_binary_number(decimal_number : int):
    assert isinstance(decimal_number, int)
    return bin(decimal_number)

print(get_binary_number(10.0))

AssertionError: 

### File Handling

In [ ]:
f = open("i_have_a_dream.txt", "r")
contents = f.read()
 print(contents)
f.close()

In [ ]:
with f = open("i_have_a_dream.txt", "r") as f
    contents = f.read()
    print(contents)
print(f)

In [ ]:
with open("i_have_a_dream.txt", "r") as f:
    content_list = f.readlines()
content_list[0]

In [ ]:
with open("i_have_a_dream.txt", "r") as f:
    i = 0
    while True:
        line = f.readline()
        if i == 5:
            break
        print("[0] ==== {1}".format(i, line))
        i += 1
line

In [ ]:
with open("i_have_a_dream.txt", "r") as my_file:
    contents = my_file.read()
    word_list = contents.split(" ")
    line_list = contents.split("\n")

print("Total Number of Characters : ", len(contents))
print("Total Number of Words : ", len(word_list))
print("Total Number of Lines : ", len(line_list))

### File Write

In [6]:
f = open("count_log.txt", mode='w', encoding="utf8")
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" %i
    f.write(data)
f.close()

In [8]:
with open("count_log.txt", mode='a', encoding="utf8") as f:
    for i in range(11, 21):
        data = "{0}번째 줄입니다. \n".format(i)
        f.write(data)

### Directory 다루기

#### os모듈을 사용하여 Directory 다루기

In [9]:
import os
os.mkdir("log")

In [10]:
try:
    os.mkdir("log")
except FileExistsError as e:
    print("Already created")

Already created


In [12]:
os.path.exists("log")

True

In [14]:
import shutil

source = 'i_have_a_dream.txt'
dest = os.path.join("abc", "sungchul.txt") # "abc" + "\\" + "sungchul.txt"

shutil.copy(source, dest) # shutil.copy : 파일 복사 함수

FileNotFoundError: [Errno 2] No such file or directory: 'i_have_a_dream.txt'

In [18]:
import pathlib
cwd = pathlib.Path.cwd()
cwd

WindowsPath('C:/Users/soomanhong/Desktop')

In [19]:
cwd.parent

WindowsPath('C:/Users/soomanhong')

In [20]:
cwd.parent.parent

WindowsPath('C:/Users')

In [21]:
list(cwd.parent.parents)

[WindowsPath('C:/Users'), WindowsPath('C:/')]

In [23]:
list(cwd.glob("*"))

[WindowsPath('C:/Users/soomanhong/Desktop/.ipynb_checkpoints'),
 WindowsPath('C:/Users/soomanhong/Desktop/Cisco Webex Meetings.lnk'),
 WindowsPath('C:/Users/soomanhong/Desktop/count_log.txt'),
 WindowsPath('C:/Users/soomanhong/Desktop/desktop.ini'),
 WindowsPath('C:/Users/soomanhong/Desktop/Discord.lnk'),
 WindowsPath('C:/Users/soomanhong/Desktop/DroidCamApp.lnk'),
 WindowsPath('C:/Users/soomanhong/Desktop/GitHub Desktop.lnk'),
 WindowsPath('C:/Users/soomanhong/Desktop/Hancom'),
 WindowsPath('C:/Users/soomanhong/Desktop/HNY'),
 WindowsPath('C:/Users/soomanhong/Desktop/Intech_LauncherExe.exe.lnk'),
 WindowsPath('C:/Users/soomanhong/Desktop/KakaoTalk_20211004_202018006.mp4'),
 WindowsPath('C:/Users/soomanhong/Desktop/KakaoTalk_20220525_125758936.mp4'),
 WindowsPath('C:/Users/soomanhong/Desktop/KakaoTalk_20220525_125856316.mp4'),
 WindowsPath('C:/Users/soomanhong/Desktop/KakaoTalk_20220525_125959657.mp4'),
 WindowsPath('C:/Users/soomanhong/Desktop/log'),
 WindowsPath('C:/Users/soomanhong/

In [28]:
import os
if not os.path.exists("log"):
    os.mkdir("log")

TARGET_FILE_PATH = os.path.join("log", "count_log.txt")
if not os.path.exists(TARGET_FILE_PATH):
    f = open("log/count_log.txt", 'w', encoding="utf8")
    f.write("기록이 시작됩니다\n")
    f.close

In [29]:
with open(TARGET_FILE_PATH, 'a', encoding="utf8") as f:
    import random, datetime
    for i in range(1,11):
        stamp = str(datetime.datetime.now())
        value = random.random() * 1000000
        log_line = stamp + "\t" + str(value) + "값이 생성되었습니다\n"
        f.write(log_line)

### Pickle

In [30]:
import pickle

f = open("list.pickle", 'wb')
test = {1,2,3,4,5}
pickle.dump(test, f)
f.close()

In [31]:
del test

In [32]:
test

NameError: name 'test' is not defined

In [33]:
f = open("list.pickle", "rb")
test_pickle = pickle.load(f)
print(test_pickle)
f.close()

{1, 2, 3, 4, 5}


In [34]:
test_pickle

{1, 2, 3, 4, 5}

In [53]:
class Multiply(object):
    def __init__(self, multiplier):
        self.multiplier = multiplier
    
    def multiply(self, number):
        return number * self.multiplier

In [54]:
muliply = Multiply(5)
muliply.multiply(100)

500

In [55]:
muliply

In [57]:
f = open("multiply_object.pickle", 'wb')
pickle.dump(muliply, f)
f.close()

In [58]:
del muliply

In [59]:
f = open("multiply_object.pickle", 'rb')
multiply_pickle = pickle.load(f)
multiply_pickle.multiply(100)

500

### Logging Handling

In [60]:
import logging

logging.debug("틀렸어!!")
logging.info("확인행!!")
logging.warning("조심해!!")
logging.error("에러났어!!")
logging.critical("망했다!!")

# 기본 logging level이 warning 이기 때문에 warning 부터 출력

ERROR:root:에러났어!!
CRITICAL:root:망했다!!


In [73]:
import logging

if __name__ == '__main__':
    logger = logging.getLogger("main")
    logging.basicConfig(level = logging.DEBUG)
    #logger.setLevel(logging.INFO)
    
    steam_handler = logging.FileHandler(
          "my.log", mode="a", encoding="utf8")
    
    logger.addHandler(steam_handler)
    
    logger.debug("틀렸어!!")
    logger.info("확인행!!")
    logger.warning("조심해!!")
    logger.error("에러났어!!")
    logger.critical("망했다!!")

INFO:main:확인행!!
ERROR:main:에러났어!!
CRITICAL:main:망했다!!


In [74]:
cat my.log

SyntaxError: invalid syntax (<ipython-input-74-be4d0cc064a9>, line 1)

In [1]:
# CSV 파일 읽기 예제

line_counter = 0
data_header = []
customer_list = []

with open ("customers.csv") as customer_data:
    while True:
        data = customer_data.readline()
        if not data: break
        if line_counter==0:
            data_header = data.split(",")
        else:
            customer_list.append(data.split(","))
        line_counter += 1
        
print("Header :\t", data_header)

for i in range(0,10):
    print ("Data",i,":\t\t",customer_list[i])
print (len(customer_list))

Header :	 ['customerNumber', 'customerName', 'contactLastName', 'contactFirstName', 'phone', 'addressLine1', 'addressLine2', 'city', 'state', 'postalCode', 'country', 'salesRepEmployeeNumber', 'creditLimit\n']
Data 0 :		 ['103', '"Atelier graphique"', 'Schmitt', '"Carine "', '40.32.2555', '"54', ' rue Royale"', 'NULL', 'Nantes', 'NULL', '44000', 'France', '1370', '21000\n']
Data 1 :		 ['112', '"Signal Gift Stores"', 'King', 'Jean', '7025551838', '"8489 Strong St."', 'NULL', '"Las Vegas"', 'NV', '83030', 'USA', '1166', '71800\n']
Data 2 :		 ['114', '"Australian Collectors', ' Co."', 'Ferguson', 'Peter', '"03 9520 4555"', '"636 St Kilda Road"', '"Level 3"', 'Melbourne', 'Victoria', '3004', 'Australia', '1611', '117300\n']
Data 3 :		 ['119', '"La Rochelle Gifts"', 'Labrune', '"Janine "', '40.67.8555', '"67', ' rue des Cinquante Otages"', 'NULL', 'Nantes', 'NULL', '44000', 'France', '1370', '118200\n']
Data 4 :		 ['121', '"Baane Mini Imports"', 'Bergulfsen', '"Jonas "', '"07-98 9555"', '"E

In [3]:
# CSV 파일 쓰기 예제

line_counter = 0
data_header = []
employee = []
customer_USA_only_list = []
customer = None

with open ("customers.csv", "r") as customer_data:
    while 1:
        data = customer_data.readline()
        if not data:
            break
        if line_counter==0:
            data_header = data.split(",")
        else:
            customer = data.split(",")
            if customer[10].upper() == "USA":
                customer_USA_only_list.append(customer)
        line_counter += 1
        
print("Header : \t", data_header)
for i in range(0,10):
    print("Data : \t\t", customer_USA_only_list[i])
print(len(customer_USA_only_list))

with open("customers_USA_only.csv", "w") as customer_USA_only_csv:
    for customer in customer_USA_only_list:
        customer_USA_only_csv.write(",".join(customer).strip('\n')+"\n")

Header : 	 ['customerNumber', 'customerName', 'contactLastName', 'contactFirstName', 'phone', 'addressLine1', 'addressLine2', 'city', 'state', 'postalCode', 'country', 'salesRepEmployeeNumber', 'creditLimit\n']
Data : 		 ['112', '"Signal Gift Stores"', 'King', 'Jean', '7025551838', '"8489 Strong St."', 'NULL', '"Las Vegas"', 'NV', '83030', 'USA', '1166', '71800\n']
Data : 		 ['124', '"Mini Gifts Distributors Ltd."', 'Nelson', 'Susan', '4155551450', '"5677 Strong St."', 'NULL', '"San Rafael"', 'CA', '97562', 'USA', '1165', '210500\n']
Data : 		 ['129', '"Mini Wheels Co."', 'Murphy', 'Julie', '6505555787', '"5557 North Pendale Street"', 'NULL', '"San Francisco"', 'CA', '94217', 'USA', '1165', '64600\n']
Data : 		 ['131', '"Land of Toys Inc."', 'Lee', 'Kwai', '2125557818', '"897 Long Airport Avenue"', 'NULL', 'NYC', 'NY', '10022', 'USA', '1323', '114900\n']
Data : 		 ['151', '"Muscle Machine Inc"', 'Young', 'Jeff', '2125557413', '"4092 Furth Circle"', '"Suite 400"', 'NYC', 'NY', '10022', 

In [ ]:
import csv

seoung_nam_data = []
header = []
rownum = 0

with open("korea_floating_population_data.csv","r", encoding="cp949") as p_file:
    csv_data = csv.reader(p_file)
    for row in csv_data:
        if rownum == 0:
            header = row
        location = row[7]

        if location.find(u"성남시") != -1:
            seoung_nam_data.append(row)
        rownum +=1
with open("seoung_nam_floating_population_data.csv","w", encoding="utf8") as s_p_file:
    writer = csv.writer(s_p_file, delimiter='\t', quotechar="'", quoting=csv.QUOTE_ALL)
    writer.writerow(header) 
    for row in seoung_nam_data:
        writer.writerow(row)

### Web

In [7]:
import re
import urllib.request

url = "https://bit.ly/3rxQFS4"
html = urllib.request.urlopen(url)
html_contents = str(html.read())
id_results = re.findall(r"([A-Za-z0-9]+\*\*\*)", html_contents)
#findall 전체 찾기, 패턴대로 데이터 찾기
print(id_results)
for result in id_results:
    print(result)

['codo***', 'outb7***', 'dubba4***', 'multicuspi***', 'crownm***', 'triformo***', 'spania***', 'magazin***', 'presby***', 'trophody***', 'nontr***', 'enranck***', 'canc***', 'uncanker***', 'wrymo***', 'non***', 'luminat***', 'oblig***', 'anna***', 'hyperth***', 'toplabl***', 'dolce0***', 'rudals2***', 'jjw980***', 'elvlz***', 'skmid***', 'qkep***', 'kisslov***', 'maskman***', 'sungt***']
codo***
outb7***
dubba4***
multicuspi***
crownm***
triformo***
spania***
magazin***
presby***
trophody***
nontr***
enranck***
canc***
uncanker***
wrymo***
non***
luminat***
oblig***
anna***
hyperth***
toplabl***
dolce0***
rudals2***
jjw980***
elvlz***
skmid***
qkep***
kisslov***
maskman***
sungt***


In [8]:
import urllib.request # urllib 모듈 호출
import re

url = "http://www.google.com/googlebooks/uspto-patents-grants-text.html" #url 값 입력
html = urllib.request.urlopen(url) # url 열기
html_contents = str(html.read().decode("utf8")) # html 파일 읽고, 문자열로 변환

url_list = re.findall(r"(http)(.+)(zip)", html_contents)
for url in url_list:
    print("".join(url)) # 출력된 Tuple 형태 데이터 str으로 join

http://storage.googleapis.com/patents/grant_full_text/2015/ipg150106.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150113.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150120.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150127.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150203.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150210.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150217.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150224.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150303.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150310.zip
http://storage.googleapis.com/patents/grant_full_text/2015/ipg150317.zip
http://storage.googleapis.com/patents/grant_full_text/2014/ipg140107.zip
http://storage.googleapis.com/patents/grant_full_text/2014/ipg140114.zip
http://storage.googleapis.com/patents/grant_full_te

http://storage.googleapis.com/patents/grant_full_text/2007/ipg070213.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070220.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070227.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070306.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070313.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070320.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070327.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070403.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070410.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070417.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070424.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070501.zip
http://storage.googleapis.com/patents/grant_full_text/2007/ipg070508.zip
http://storage.googleapis.com/patents/grant_full_te

In [9]:
import urllib.request
import re

url = "http://finance.naver.com/item/main.nhn?code=005930"
html = urllib.request.urlopen(url)
html_contents = str(html.read().decode("ms949"))

stock_results = re.findall("(\<dl class=\"blind\"\>)([\s\S]+?)(\<\/dl\>)", html_contents)
samsung_stock = stock_results[0] # 두 개 tuple 값중 첫번째 패턴
samsung_index = samsung_stock[1] # 세 개의 tuple 값중 두 번째 값
                                # 하나의 괄호가 tuple index가 됨
index_list= re.findall("(\<dd\>)([\s\S]+?)(\<\/dd\>)", samsung_index)
for index in index_list:
    print (index[1]) # 세 개의 tuple 값중 두 번째 값

2022년 07월 19일 16시 11분 기준 장마감
종목명 삼성전자
종목코드 005930 코스피
현재가 60,900 전일대비 하락 1,000 마이너스 1.62 퍼센트
전일가 61,900
시가 61,400
고가 61,500
상한가 80,400
저가 60,200
하한가 43,400
거래량 15,140,679
거래대금 919,379백만


### Numpy

In [1]:
import numpy as np

In [6]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

In [7]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [8]:
test_array = np.array(["1", "4", 5.0, 8], float) # String Type의 데이터를 입력해도
test_array

array([ 1.,  4.,  5.,  8.])

In [10]:
type(test_array)

numpy.ndarray

In [11]:
type(test_array[3]) # Float Type으로 자동 형변환을 실시

numpy.float64

In [12]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1] # 'is'는 메모리의 위치를 판별

True

In [13]:
a is b

False

In [14]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [15]:
test_array.dtype

dtype('float64')

In [16]:
a = [[1, 2, 3], [4, 5, 6,], [7, 8, 9]]

In [17]:
np.array(a).shape

(3, 3)

#### .array shape

In [18]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [21]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [22]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor, int).shape

(4, 3, 4)

In [23]:
np.array(tensor, int).ndim # number of dimensions

3

In [24]:
np.array(tensor, int).size

48

#### .numpy dtype

In [26]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=np.int8)

In [27]:
a.dtype

dtype('int8')

In [28]:
np.array([[1, 2, 3],  [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [29]:
np.array([[1, 2, 3],  [4.5, "5", "6"]], dtype=np.int32).nbytes

24

In [30]:
np.array([[1, 2, 3],  [4.5, "5", "6"]], dtype=np.int8).nbytes

6

In [31]:
np.array([[1, 2, 3],  [4.5, "5", "6"]], dtype=np.float64).nbytes

48

### Handling shape

#### .reshape

In [2]:
import numpy as np

test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [4]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [5]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [6]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [7]:
np.array(test_matrix).reshape(2,2,2) # 결과가 출력됐을 뿐

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [8]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [9]:
np.array(test_matrix).reshape(2,-1,2).shape

(2, 2, 2)

In [10]:
np.array(test_matrix).reshape(1,-1,2).shape

(1, 4, 2)

In [11]:
test_matrix # 할당되지 않았기 때문에 test_matrix 자체는 바뀌지 않음

[[1, 2, 3, 4], [1, 2, 5, 8]]

In [14]:
np.array(test_matrix).reshape(1,-1)

array([[1, 2, 3, 4, 1, 2, 5, 8]])

In [15]:
 np.array(test_matrix).reshape(1,-1).shape

(1, 8)

In [17]:
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [18]:
test_matrix

[[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]

In [22]:
test_matrix = np.array(test_matrix)
test_matrix.shape

(2, 2, 4)

In [23]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [24]:
np.array(test_matrix).flatten().shape

(16,)

In [21]:
np.array(test_matrix).flatten().size

16

#### .indexing & slicing

In [26]:
test_example = np.array([[1,2,3], [4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
test_example[0][2]

3

In [28]:
test_example[0,2]

3

In [29]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [30]:
test_example[1,2] = 5
test_example[1,2]

5

In [31]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)

In [32]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [34]:
a[1,1:3]

array([7, 8])

In [35]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [36]:
a[1]

array([ 6,  7,  8,  9, 10])

In [37]:
a[1:2]

array([[ 6,  7,  8,  9, 10]])

In [38]:
a[0]

array([1, 2, 3, 4, 5])

In [45]:
a[:,:1]

array([[1],
       [6]])

In [46]:
test_example = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8], [1,2,5,8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [47]:
test_example[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [48]:
test_example # test_example 자체가 바뀌지 않음

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [49]:
test_example[:, 1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [50]:
test_example[:, 1:3].shape

(4, 2)

In [51]:
test_example[1:2, :2]

array([[1, 2]])

In [52]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
test_example[1] # 1 dimension으로 나옴

array([ 6,  7,  8,  9, 10])

In [54]:
test_example[1:3] # 2 dimension으로 나옴

array([[ 6,  7,  8,  9, 10]])

In [56]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

#### .creation function

In [59]:
list(range(0,10,3))

[0, 3, 6, 9]

In [60]:
type(list(range(30)))

list

#### ..arange

In [61]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [62]:
np.arange(0, 10, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [63]:
np.arange(0, 5, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [64]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### ..ones, zeros & empty

In [66]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [67]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [68]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [69]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [78]:
np.empty(shape=(10,), dtype=np.int8)

array([-107,    0,    0,    0,  114,    9,    0,    0,  -16, -109], dtype=int8)

In [86]:
np.empty((10,5))

array([[  2.12199579e-314,   6.36598737e-314,   1.06099790e-313,
          1.48539705e-313,   1.90979621e-313],
       [  2.33419537e-313,   2.75859453e-313,   3.18299369e-313,
          3.60739285e-313,   4.03179200e-313],
       [  4.45619116e-313,   4.88059032e-313,   5.30498948e-313,
          5.72938864e-313,   6.15378780e-313],
       [  6.57818695e-313,   7.00258611e-313,   7.42698527e-313,
          7.85138443e-313,   8.27578359e-313],
       [  8.70018274e-313,   9.12458190e-313,   9.54898106e-313,
          9.97338022e-313,   1.03977794e-312],
       [  1.08221785e-312,   1.12465777e-312,   1.16709769e-312,
          1.20953760e-312,   1.25197752e-312],
       [  1.29441743e-312,   1.33685735e-312,   1.37929726e-312,
          1.42173718e-312,   1.46417710e-312],
       [  1.50661701e-312,   1.54905693e-312,   1.59149684e-312,
          1.63393676e-312,   1.67637668e-312],
       [  1.71881659e-312,   1.76125651e-312,   1.80369642e-312,
          1.84613634e-312,   1.88857625

 #### ..something _like

In [87]:
test_matrix = np.arange(100).reshape(5, -1)
test_matrix.shape

(5, 20)

In [89]:
test_matrix


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99]])

In [90]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [91]:
np.ones_like(test_matrix, dtype=np.float32)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [94]:
np.empty_like(test_matrix, dtype=np.float32)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

#### ..eye, identity & digonal

In [95]:
np.identity(n = 5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [96]:
np.eye(N = 3, M = 5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [97]:
np.eye(N = 3, M = 5, k=2, dtype=np.int8)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [98]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [99]:
np.eye(3, 5, k=2)

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [101]:
matrix = np.arange(12).reshape(3,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
np.diag(matrix, k=2)

array([2, 7])

#### ..numpy.random

In [103]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.2440134 , -1.52936808, -0.35052042,  0.15232942, -0.34829893],
       [ 0.17599831, -0.14327957,  0.74420503, -0.10454721,  0.88594801]])

In [104]:
np.random.exponential(scale=2, size=100)

array([  2.21732517e-01,   4.89540072e-02,   1.51342906e+00,
         6.12524095e+00,   5.15516400e+00,   2.88462379e+00,
         8.12963761e-01,   2.96786778e+00,   5.65162698e-01,
         5.30551454e+00,   2.08613745e+00,   3.17091657e+00,
         1.04692345e+00,   4.64604303e-01,   2.65982476e+00,
         9.94951145e-02,   1.05930132e+00,   3.92077314e-01,
         1.51794495e+00,   1.10641159e-01,   1.23380990e+00,
         1.06432901e-01,   2.11641695e+00,   4.15073642e+00,
         1.36019968e-01,   1.06264011e+00,   2.44071378e+00,
         1.20377585e+00,   1.58568689e+00,   4.42714365e-01,
         9.41656560e-01,   2.53060533e+00,   6.54480443e-01,
         1.51894839e+00,   2.46033229e+00,   2.92938043e+00,
         2.53713883e+00,   5.23640988e+00,   2.56217974e+00,
         6.49742454e-01,   6.33644622e-02,   2.53804533e+00,
         1.09705679e+00,   4.43452325e-01,   1.83120565e+00,
         7.78516843e+00,   1.72986148e+00,   4.04932341e+00,
         1.57991043e+00,

#### .operation functions

#### ..sum

In [105]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
test_array.sum(dtype=np.float)

55.0

In [107]:
sum(test_array)

55

#### ..axis

In [108]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [110]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [111]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [112]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

#### .. mathematical functions

In [113]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
test_array.mean(axis=1)

array([  2.5,   6.5,  10.5])

In [116]:
test_array.std(axis=0), test_array.std(axis=1)

(array([ 3.26598632,  3.26598632,  3.26598632,  3.26598632]),
 array([ 1.11803399,  1.11803399,  1.11803399]))

In [117]:
np.sqrt(test_array)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712],
       [ 3.        ,  3.16227766,  3.31662479,  3.46410162]])

In [118]:
np.exp(test_array)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
          5.45981500e+01],
       [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
          2.98095799e+03],
       [  8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
          1.62754791e+05]])

 #### ..Concatenate

In [119]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [122]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [124]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [125]:
a = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])
np.concatenate((a,b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [138]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
a


array([[1, 2],
       [3, 4]])

In [139]:
b

array([5, 6])

In [140]:
b = b[np.newaxis, :] # a의 dimension을 맞추기 위해 축을 하나 추가한다
b

array([[5, 6]])

In [141]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

#### ..Opreations b/t arrays

In [144]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [145]:
test_a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [146]:
test_a + test_a

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [147]:
test_a - test_a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

#### ..Element-wise operations

In [148]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a - matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [149]:
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

#### ..dot product

In [150]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [151]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [152]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

#### ..transpose

In [153]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [155]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

#### ..broadcasting

In [157]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [158]:
test_matrix + scalar

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [159]:
test_matrix * 5

array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

In [160]:
test_matrix / 5

array([[ 0.2,  0.4,  0.6],
       [ 0.8,  1. ,  1.2]])

In [161]:
test_matrix // 0.2

array([[  4.,   9.,  14.],
       [ 19.,  24.,  29.]])

In [162]:
test_matrix ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [163]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

#### .comparisons

#### ..All & Any

In [165]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False, False], dtype=bool)

In [167]:
a < 1

array([ True, False, False, False, False, False, False, False, False, False], dtype=bool)

In [168]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [169]:
np.all(a<10)

True

In [170]:
np.all(a < 5)

False

In [171]:
np.any(a > 5)

True

In [172]:
np.any(a < 0)

False

In [174]:
test_a = np.array([1,3,0],float) 
test_b = np.array([5,2,1],float) 
test_a > test_b

array([False,  True, False], dtype=bool)

In [175]:
test_a == test_b

array([False, False, False], dtype=bool)

In [177]:
(test_a > test_b).any()

True

In [179]:
a =test_a = np.array([1,3,0],float)
np.logical_and(a>0, a<3)

array([ True, False, False], dtype=bool)

In [180]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False], dtype=bool)

In [181]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True,  True], dtype=bool)

#### ..np.where

In [182]:
 a

array([ 1.,  3.,  0.])

In [183]:
np.where(a>5)

(array([], dtype=int64),)

In [184]:
np.where(a>2) # index 반환

(array([1], dtype=int64),)

In [189]:
np.where(a<3)[0]

array([0, 2], dtype=int64)

In [190]:
np.where(a<3, 3, 2) # True이면 3, False이면 2

array([3, 2, 3])

In [191]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [192]:
np.where(a > 10) # 10보다 큰 값의 인덱스 반환

(array([6, 7, 8, 9], dtype=int64),)

In [194]:
a = np.array([1, np.NaN, np.Inf],float)
np.isnan(a)

array([False,  True, False], dtype=bool)

In [195]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

#### ..argmax & argmin

In [199]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a) # index 반환

(5, 0)

In [200]:
a.argsort() # index 반환

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [201]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

#### .boolean & fancy index

In [202]:
test_array = np.array([1,4,0,2,3,8,9,7], float)

In [203]:
test_array > 3

array([False,  True, False, False, False,  True,  True,  True], dtype=bool)

In [204]:
test_array[test_array > 3] # 조건이 True인 index의 element만 추출

array([ 4.,  8.,  9.,  7.])

In [205]:
condition = test_array < 3
test_array[condition]

array([ 1.,  0.,  2.])

#### ..fancy index

In [206]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [207]:
a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [208]:
a = np.array([2,4,6,8], float)
cond = np.array([1,1,1,2,1,1,1,3])
a[cond]

array([ 4.,  4.,  4.,  6.,  4.,  4.,  4.,  8.])

In [209]:
a = np.array([2,4,6,8], float)
cond = np.array([1,1,1,2,1,1,1,5]) # 0~3 밖의 값이 존재하기 때문에 에러
a[cond]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [210]:
a = np.array([[1,4],[9,16]],float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([  1.,   4.,  16.,  16.,   4.])

In [211]:
a = np.array([[1,4],[9,16]],float)
a[b]

array([[  1.,   4.],
       [  1.,   4.],
       [  9.,  16.],
       [  9.,  16.],
       [  1.,   4.]])

#### .numpy data i/o

#### .. loadtxt & savetxt

In [212]:
a = np.loadtxt("./population.txt", delimiter = "\t")
a[:10]

FileNotFoundError: [Errno 2] No such file or directory: './population.txt'

In [214]:
a_int = a.astype(int)
a_int_3 = a_int[:3]

In [ ]:
np.savetxt("int_data_2.csv", a_int_3, fmt = "%.2e", delimiter=",")

#### ..numpy object - npy

In [216]:
np.save("npy_test_object", arr = a_int_3) # pickle 형식

In [217]:
a_test = np.load(file="npy_test.npy")
a_test

FileNotFoundError: [Errno 2] No such file or directory: 'npy_test.npy'

In [218]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

FileNotFoundError: [Errno 2] No such file or directory: 'npy_test.npy'